Chore/fix dao tests and dummy data
8ball030/auto_dev pull request #361
Opened 2024-11-29 23:17 UTC by xiuxiuxar

Resolves #355

2024-11-30 08:03 UTC, 8ball030 requested changes
Please remove the necessary functions and use the hashbmap from the contract scffolding to take you from python type to random value.
This will remove a lot of lines

2024-11-30 08:03 UTC, 8ball030 commented on auto_dev/commands/scaffold.py
> +        return
raise here as it wont work right

2024-11-30 08:03 UTC, 8ball030 commented on auto_dev/commands/scaffold.py
> +        return
same

2024-11-30 08:03 UTC, 8ball030 commented on auto_dev/dao/dummy_data.py
>  def generate_integer() -> int:
This is already present in a the contract stuff, so you can go from a type to a random value

2024-11-30 08:03 UTC, 8ball030 commented on auto_dev/dao/dummy_data.py
> +    return [_generate_model_dummy_data(item_schema) for _ in range(2)]
Why do we need 2 of the same test?

2024-12-10 05:37 UTC, 8ball030 requested changes

2024-12-10 05:37 UTC, 8ball030 commented on auto_dev/dao/dummy_data.py
> +TYPE_TO_GENERATORS = {
There is already a mapping from type to example. 
Please use this rather than adding more of the same thing

2025-01-06 23:04 UTC, xiuxiuxar commented on auto_dev/dao/dummy_data.py
> +TYPE_TO_GENERATORS = {
mapping in contracts/utils will not work.  need openapi specific data types

2025-01-07 13:53 UTC, merged